CORPUS = [
    "OpenAI được thành lập bởi Sam Altman và Elon Musk vào năm 2015. OpenAI phát triển mô hình GPT-4 và ChatGPT.",
    "Google được thành lập bởi Larry Page và Sergey Brin vào năm 1998. Google phát triển mô hình Gemini và sản phẩm Google Search.",
    "Microsoft được thành lập bởi Bill Gates và Paul Allen vào năm 1975. Microsoft đầu tư vào OpenAI và phát triển Azure.",
    "Meta được thành lập bởi Mark Zuckerberg vào năm 2004. Meta phát triển mô hình LLaMA và sản phẩm Facebook, Instagram.",
    "Anthropic được thành lập bởi Dario Amodei và Daniela Amodei vào năm 2021. Anthropic phát triển mô hình Claude.",
    "Sam Altman là CEO của OpenAI. Sam Altman từng làm việc tại Y Combinator.",
    "Elon Musk cũng thành lập Tesla và SpaceX. Elon Musk rời khỏi ban điều hành OpenAI vào năm 2018.",
    "Google thuộc tập đoàn Alphabet. Alphabet được thành lập vào năm 2015.",
    "Microsoft hợp tác với OpenAI để tích hợp GPT-4 vào Bing và Office 365.",
    "Dario Amodei từng là VP Research tại OpenAI trước khi thành lập Anthropic.",
    "Apple được thành lập bởi Steve Jobs, Steve Wozniak và Ronald Wayne vào năm 1976. Apple phát triển hệ sinh thái iOS và macOS.",
    "Amazon được thành lập bởi Jeff Bezos vào năm 1994. Amazon phát triển dịch vụ đám mây AWS và đầu tư vào Anthropic.",
    "Ilya Sutskever từng là Chief Scientist tại OpenAI trước khi rời đi vào năm 2024 để thành lập Safe Superintelligence.",
    "xAI được thành lập bởi Elon Musk vào năm 2023. xAI phát triển mô hình ngôn ngữ Grok.",
    "Mistral AI là một công ty AI của Pháp được thành lập vào năm 2023 bởi Arthur Mensch. Mistral AI phát triển mô hình Mistral Large.",
]
